env:
  es6: true
  node: true
  mocha: true

root: true

rules:
  no-var: "error"
  no-cond-assign: ["error", "except-parens"]
  no-trailing-spaces: ["error", { "skipBlankLines": false }]
  no-empty: [ "error", { "allowEmptyCatch": true } ]
  no-shadow: "error"
  prefer-template: "warn"

extends: ["eslint:recommended"]
